var translations = {
    "es": {
        "navInicio": "Inicio",
        "weblog": "Weblog",
        "now": "Now",
        "footerText": "© 2022-2026 ruflas | licenciado bajo <a href='https://creativecommons.org/licenses/by-sa/4.0/' target='_blank'>CC BY-SA</a> 😽",
        "postTitle": "Homelab",
        "postDate": "Publicado el 05 de mayo de 2026",
        "introduction": "He decidido montar mi propio homelab como un entorno dedicado a la experimentación y el aprendizaje en ciberseguridad, desarrollo y administración de sistemas.",
        "motivationTitle": "Motivación",
        "motivation": "Un homelab es una herramienta fundamental para cualquier persona apasionada por la ciberseguridad y la administración de sistemas. Me permite probar nuevas tecnologías, practicar técnicas de hacking ético, configurar servicios y perfeccionar mis habilidades en un entorno seguro y controlado, eliminando el riesgo de afectar sistemas en producción.",
        "hardwareTitle": "Hardware",
        "hardwareIntro": "El núcleo de mi laboratorio está construido con componentes cuidadosamente seleccionados para ofrecer un rendimiento óptimo:",
        "hw1": "<strong>Chasis:</strong> Jonsbo N4 - un diseño compacto pero con excelente capacidad.",
        "hw2": "<strong>Procesador:</strong> Intel Xeon E5 2680 V4 - 14 núcleos y 28 hilos, ideal para cargas intensivas de virtualización.",
        "hw3": "<strong>Memoria:</strong> 32GB RAM ECC DDR4 - fundamental para garantizar la estabilidad del sistema y la integridad de los datos.",
        "hw4": "<strong>Placa Base:</strong> X99 Machinist - excelente soporte para expansión y múltiples recursos.",
        "hw5": "<strong>GPU:</strong> NVIDIA GT 710 - dedicada exclusivamente a la salida de vídeo.",
        "serverSpecs": "Esta configuración me proporciona la potencia necesaria para ejecutar múltiples máquinas virtuales y contenedores de forma simultánea, sin sufrir degradación en el rendimiento. El procesador Xeon E5 resulta una pieza clave para manejar estas exigentes cargas de trabajo.",
        "virtualizationTitle": "Virtualización con Proxmox VE",
        "virtualizationContent": "Como hipervisor utilizo Proxmox VE, una potente plataforma de virtualización de código abierto basada en KVM. Proxmox me facilita:",
        "virt1": "Crear y administrar máquinas virtuales complejas basadas en Linux.",
        "virt2": "Ejecutar contenedores LXC para aplicaciones que requieren menos recursos.",
        "virt3": "Programar snapshots y copias de seguridad de forma automática.",
        "virt4": "Migrar máquinas virtuales en caliente sin tiempo de inactividad (downtime).",
        "servicesTitle": "Servicios y Aplicaciones",
        "servicesIntro": "Tengo ahora mismo estos servicios importantes montados de cara al uso y análisis de red/servidor:",
        "service1": "<strong>Nginx:</strong> Proxy inverso y balanceador de carga que enruta el tráfico hacia mis aplicaciones.",
        "service2": "<strong>AdGuard Home:</strong> Servidor DNS que bloquea rastreadores y anuncios en toda mi red doméstica.",
        "service3": "<strong>Dockge:</strong> Panel de control intuitivo para gestionar mis contenedores y stacks de docker-compose.",
        "service4": "<strong>Gitea:</strong> Servidor Git autoalojado para llevar el control de versiones de forma privada y paralela a GitHub.",
        "service5": "<strong>Uptime Kuma:</strong> Herramienta de monitorización para verificar el estado y la disponibilidad de mis servicios.",
        "service6": "<strong>Glances:</strong> Dashboard que muestra las estadísticas y el consumo de recursos del servidor en tiempo real.",
        "service7": "<strong>Scrutiny:</strong> Monitorización de los datos SMART de mis discos duros para anticiparme a posibles fallos.",
        "storageTitle": "Almacenamiento",
        "storageContent": "El almacenamiento es un pilar crítico para que el homelab sea seguro y funcional. Para ello, he configurado:",
        "stor1": "<strong>RAID ZFS:</strong> 4 discos de 1TB en configuración RAID-Z1, asegurando tolerancia a fallos.",
        "stor2": "<strong>Capacidad Total:</strong> 4TB de almacenamiento crudo, optimizado para backups, datos y multimedia con redundancia.",
        "stor3": "<strong>Snapshots ZFS:</strong> Protección instantánea contra borrados accidentales, ransomware o corrupción de datos.",
        "stor4": "<strong>Automatización:</strong> Tareas programadas para el respaldo de máquinas virtuales e información crítica.",
        "automationTitle": "Automatización y Scripts",
        "automationContent": "La automatización resulta clave para minimizar el trabajo manual y evitar tareas repetitivas:",
        "auto1": "Scripts de Bash personalizados para agilizar la administración diaria.",
        "auto2": "Uso intensivo de docker-compose para garantizar despliegues consistentes y reproducibles.",
        "auto3": "Copias de seguridad desatendidas para proteger configuraciones y máquinas virtuales.",
        "auto4": "Sistemas de alerta que me notifican automáticamente si algún servicio presenta problemas.",
        "learningTitle": "Experiencia de Aprendizaje",
        "learningContent": "Este homelab va mucho más allá de ser una simple infraestructura; es un laboratorio vivo en el que sigo aprendiendo día a día:",
        "learn1": "Administración avanzada de sistemas Linux en escenarios realistas.",
        "learn2": "Virtualización y orquestación de contenedores empleando Proxmox y Docker.",
        "learn3": "Aplicación de medidas de seguridad (hardening) y buenas prácticas en redes.",
        "learn4": "Gestión de infraestructura como código mediante automatización y scripting.",
        "learn5": "Despliegue de proyectos de desarrollo simulando entornos de producción reales.",
        "objectivesTitle": "Objetivos Principales",
        "objectivesContent": "El propósito fundamental de este proyecto es alcanzar una mayor independencia y tener un control absoluto sobre mi propia tecnología:",
        "obj1": "<strong>Independencia digital:</strong> Reducir la dependencia de servicios de terceros y gigantes tecnológicos.",
        "obj2": "<strong>Autoalojamiento:</strong> Mantener mis propios servicios, datos y proyectos bajo mi propio techo.",
        "obj3": "<strong>Experimentación:</strong> Tener la libertad de \"romper\" y arreglar sistemas para entender a fondo nuevas tecnologías.",
        "obj4": "<strong>Ciberseguridad:</strong> Contar con un entorno legal y seguro para practicar tácticas de seguridad ofensiva y defensiva.",
        "obj5": "<strong>Desarrollo de Proyectos:</strong> Disponer de un ecosistema real para programar, testear y publicar aplicaciones.",
        "obj6": "<strong>Infraestructura de Calidad:</strong> Sentar unas bases sólidas en cuanto a hardware, redes y arquitectura de software.",
        "futureTitle": "Próximos Pasos",
        "futureContent": "Tengo planes bastante ambiciosos para seguir ampliando y mejorando este laboratorio:",
        "fut1": "Ampliar la capacidad de almacenamiento incorporando más discos al pool de ZFS.",
        "fut3": "Configurar un entorno aislado específico para el análisis de malware y pruebas de penetración.",
        "fut4": "Implementar alta disponibilidad (HA) y redundancia a nivel de red y servicios.",
        "fut5": "Documentar todo este proceso compartiendo guías técnicas detalladas en el blog.",
        "conclusionTitle": "Conclusión",
        "conclusion": "Este homelab representa mi compromiso con la soberanía digital y el aprendizaje continuo. No es simplemente un montón de hardware y cables, sino un entorno dinámico donde puedo investigar, equivocarme y construir sin restricciones. Gracias a tecnologías como Proxmox, Docker y Gitea, ahora tengo el control total de mi infraestructura.",
        "conclusion2": "Si buscas una forma práctica y real de potenciar tus conocimientos en sistemas, ciberseguridad o desarrollo de software, te recomiendo encarecidamente que montes tu propio homelab. La inversión de tiempo se recupera con beneficios técnicos inmediatos y duraderos.",
        "closingNote": "¿Tú también estás construyendo tu propio homelab? ¿Utilizas un stack de herramientas similar? ¡Cuéntame tu experiencia en los comentarios!",
        "cap5": "Interior: ventilador, placa X99 y RAM ECC",
        "cap4": "Chasis Jonsbo N4 con bahías de discos",
        "cap3": "Vista exterior del Jonsbo N4",
        "cap2": "Jonsbo N4 completamente montado",
        "cap6": "Pool ZFS de almacenamiento con 4 discos de 1TB",
        "cap7": "Vista general del homelab",
        "commentsSectionTitle": "Comentarios",
        "nameInputPlaceholder": "Nombre",
        "websiteInputPlaceholder": "Sitio web",
        "commentInputPlaceholder": "Comentario",
        "submitButtonText": "Publicar"
    },
    "en": {
        "navInicio": "Home",
        "weblog": "Weblog",
        "now": "Now",
        "footerText": "© 2022-2026 ruflas | licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/' target='_blank'>CC BY-SA</a> 😽",
        "postTitle": "Homelab",
        "postDate": "Published on May 5, 2026",
        "introduction": "I've decided to set up my own homelab as a dedicated environment for experimenting and learning in cybersecurity, development, and systems administration.",
        "motivationTitle": "Motivation",
        "motivation": "A homelab is a fundamental tool for anyone passionate about cybersecurity and systems administration. It allows me to test new technologies, practice ethical hacking techniques, configure services, and sharpen my skills in a safe and controlled environment, eliminating the risk of affecting production systems.",
        "hardwareTitle": "Hardware",
        "hardwareIntro": "The core of my laboratory is built with carefully selected components to offer optimal performance:",
        "hw1": "<strong>Case:</strong> Jonsbo N4 - a compact design with excellent capacity.",
        "hw2": "<strong>Processor:</strong> Intel Xeon E5 2680 V4 - 14 cores and 28 threads, ideal for intensive virtualization workloads.",
        "hw3": "<strong>Memory:</strong> 32GB ECC DDR4 RAM - essential for ensuring system stability and data integrity.",
        "hw4": "<strong>Motherboard:</strong> X99 Machinist - excellent support for expansion and multiple resources.",
        "hw5": "<strong>GPU:</strong> NVIDIA GT 710 - dedicated exclusively to video output.",
        "serverSpecs": "This configuration provides me with the power needed to run multiple virtual machines and containers simultaneously without suffering performance degradation. The Xeon E5 processor is a key piece for handling these demanding workloads.",
        "virtualizationTitle": "Virtualization with Proxmox VE",
        "virtualizationContent": "I use Proxmox VE as my hypervisor, a powerful open-source virtualization platform based on KVM. Proxmox enables me to:",
        "virt1": "Create and manage complex Linux-based virtual machines.",
        "virt2": "Run LXC containers for applications that require fewer resources.",
        "virt3": "Schedule snapshots and backups automatically.",
        "virt4": "Live-migrate virtual machines with zero downtime.",
        "servicesTitle": "Services and Applications",
        "servicesIntro": "These are the key services I currently have running for network and server use and analysis:",
        "service1": "<strong>Nginx:</strong> Reverse proxy and load balancer that routes traffic to my applications.",
        "service2": "<strong>AdGuard Home:</strong> DNS server that blocks trackers and ads across my entire home network.",
        "service3": "<strong>Dockge:</strong> Intuitive control panel for managing my containers and docker-compose stacks.",
        "service4": "<strong>Gitea:</strong> Self-hosted Git server for private version control running in parallel with GitHub.",
        "service5": "<strong>Uptime Kuma:</strong> Monitoring tool to check the status and availability of my services.",
        "service6": "<strong>Glances:</strong> Dashboard displaying server statistics and resource consumption in real time.",
        "service7": "<strong>Scrutiny:</strong> Monitoring of SMART data from my hard drives to anticipate potential failures.",
        "storageTitle": "Storage",
        "storageContent": "Storage is a critical pillar for a secure and functional homelab. For this, I have configured:",
        "stor1": "<strong>ZFS RAID:</strong> 4 x 1TB disks in RAID-Z1 configuration, ensuring fault tolerance.",
        "stor2": "<strong>Total Capacity:</strong> 4TB of raw storage, optimized for backups, data, and multimedia with redundancy.",
        "stor3": "<strong>ZFS Snapshots:</strong> Instant protection against accidental deletion, ransomware, or data corruption.",
        "stor4": "<strong>Automation:</strong> Scheduled tasks for backing up virtual machines and critical information.",
        "automationTitle": "Automation and Scripts",
        "automationContent": "Automation is key to minimizing manual work and avoiding repetitive tasks:",
        "auto1": "Custom Bash scripts to streamline daily administration.",
        "auto2": "Heavy use of docker-compose to ensure consistent and reproducible deployments.",
        "auto3": "Unattended backups to protect configurations and virtual machines.",
        "auto4": "Alert systems that automatically notify me if any service encounters issues.",
        "learningTitle": "Learning Experience",
        "learningContent": "This homelab goes far beyond being a simple infrastructure; it is a living lab where I keep learning every day:",
        "learn1": "Advanced Linux systems administration in realistic scenarios.",
        "learn2": "Virtualization and container orchestration using Proxmox and Docker.",
        "learn3": "Applying security measures (hardening) and networking best practices.",
        "learn4": "Infrastructure-as-code management through automation and scripting.",
        "learn5": "Deploying development projects simulating real production environments.",
        "objectivesTitle": "Main Objectives",
        "objectivesContent": "The fundamental purpose of this project is to achieve greater independence and have absolute control over my own technology:",
        "obj1": "<strong>Digital Independence:</strong> Reduce reliance on third-party services and tech giants.",
        "obj2": "<strong>Self-Hosting:</strong> Keep my own services, data, and projects under my own roof.",
        "obj3": "<strong>Experimentation:</strong> Have the freedom to \"break\" and fix systems to deeply understand new technologies.",
        "obj4": "<strong>Cybersecurity:</strong> Have a legal and safe environment to practice offensive and defensive security tactics.",
        "obj5": "<strong>Project Development:</strong> Have a real ecosystem to code, test, and publish applications.",
        "obj6": "<strong>Quality Infrastructure:</strong> Lay solid foundations in hardware, networking, and software architecture.",
        "futureTitle": "Next Steps",
        "futureContent": "I have ambitious plans to keep expanding and improving this lab:",
        "fut1": "Expand storage capacity by adding more disks to the ZFS pool.",
        "fut3": "Set up an isolated environment specifically for malware analysis and penetration testing.",
        "fut4": "Implement high availability (HA) and redundancy at the network and service level.",
        "fut5": "Document the entire process by sharing detailed technical guides on the blog.",
        "conclusionTitle": "Conclusion",
        "conclusion": "This homelab represents my commitment to digital sovereignty and continuous learning. It is not simply a pile of hardware and cables, but a dynamic environment where I can research, make mistakes, and build without restrictions. Thanks to technologies like Proxmox, Docker, and Gitea, I now have full control of my infrastructure.",
        "conclusion2": "If you are looking for a practical and real way to boost your knowledge in systems, cybersecurity, or software development, I strongly recommend building your own homelab. The time investment pays off with immediate and lasting technical benefits.",
        "closingNote": "Are you also building your own homelab? Do you use a similar toolstack? Tell me about your experience in the comments!",
        "cap5": "Interior: CPU fan, X99 motherboard and ECC RAM",
        "cap4": "Jonsbo N4 case with drive bays",
        "cap3": "Exterior view of the Jonsbo N4",
        "cap2": "Jonsbo N4 fully assembled",
        "cap6": "ZFS storage pool with 4 x 1TB drives",
        "cap7": "General homelab overview",
        "commentsSectionTitle": "Comments",
        "nameInputPlaceholder": "Name",
        "websiteInputPlaceholder": "Website",
        "commentInputPlaceholder": "Comment",
        "submitButtonText": "Post"
    }
};

function userLanguage() {
    var userLang = navigator.language || navigator.userLanguage;
    userLang = userLang.substring(0, 2);
    return userLang;
}

function loadLanguage() {
    var userLang = userLanguage();
    if (!translations.hasOwnProperty(userLang)) {
        userLang = "en";
    }
    document.documentElement.lang = userLang;
    if (translations.hasOwnProperty(userLang)) {
        Object.keys(translations[userLang]).forEach(function(key) {
            var element = document.getElementById(key);
            if (element) {
                element.innerHTML = translations[userLang][key];
            }
        });
        document.getElementById('nameInput').setAttribute('placeholder', translations[userLang]['nameInputPlaceholder']);
        document.getElementById('websiteInput').setAttribute('placeholder', translations[userLang]['websiteInputPlaceholder']);
        document.getElementById('commentInput').setAttribute('placeholder', translations[userLang]['commentInputPlaceholder']);
    }
}

document.addEventListener('DOMContentLoaded', loadLanguage);
